version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - dependencies
    groups:
      minor-production-deps:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
      minor-development-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      # These are all now ESM-only packages.
      - dependency-name: '@humanwhocodes/momoa'
        versions:
          - '>= 3'
      - dependency-name: chalk
        versions:
          - '>= 5'
      - dependency-name: leven
        versions:
          - '>= 4'
